server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: root
    password: secret
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate
      database-platform: org.hibernate.dialect.H2Dialect
      generate-ddl: on
      show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html

service:
  geo:
    baseUrl: https://countriesnow.space/api/v0.1/countries